import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#eff4ff",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#89ceff",
        "on-background": "#0b1c30",
        "inverse-surface": "#213145",
        "surface-container-high": "#dce9ff",
        "on-secondary-fixed": "#341100",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#783200",
        "secondary-fixed": "#ffdbca",
        "on-surface-variant": "#45464d",
        "on-tertiary-fixed": "#001e2f",
        "surface-dim": "#cbdbf5",
        secondary: "#9d4300",
        "error-container": "#ffdad6",
        "on-secondary-container": "#5c2400",
        "primary-fixed": "#dae2fd",
        "primary-container": "#131b2e",
        "on-tertiary-fixed-variant": "#004c6e",
        "primary-fixed-dim": "#bec6e0",
        "on-surface": "#0b1c30",
        background: "#f8f9ff",
        outline: "#76777d",
        "tertiary-container": "#001e2f",
        tertiary: "#000000",
        "surface-variant": "#d3e4fe",
        "outline-variant": "#c6c6cd",
        error: "#ba1a1a",
        "on-primary-fixed": "#131b2e",
        "secondary-fixed-dim": "#ffb690",
        "secondary-container": "#fd761a",
        "surface-tint": "#565e74",
        "on-tertiary-container": "#008cc7",
        "surface-container": "#e5eeff",
        "on-primary-container": "#7c839b",
        "inverse-primary": "#bec6e0",
        primary: "#000000",
        "surface-container-highest": "#d3e4fe",
        "tertiary-fixed": "#c9e6ff",
        "surface-bright": "#f8f9ff",
        "on-tertiary": "#ffffff",
        surface: "#f8f9ff",
        "inverse-on-surface": "#eaf1ff",
        "on-primary-fixed-variant": "#3f465c",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
      },
      spacing: {
        gutter: "16px",
        "section-margin": "40px",
        "card-gap": "20px",
        "container-padding": "24px",
        base: "8px",
      },
    },
  },
  plugins: [],
};
export default config;
